import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

export const metadata = {
	title: "Buity Create",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	const locale = await getLocale();
	const messages = await getMessages(); // 获取由 request.ts 提供的消息

	return (
		<html lang={locale}>
			<body>
				{/* 将 locale 和 messages 传递给客户端组件 */}
				<NextIntlClientProvider locale={locale} messages={messages}>
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
